spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5
  application:
    name: gateway-service

application:
  security:
    jwt:
      secret-key: acd57fe63f11c84ca7ba1da03d3a99bceb7427ccbb6103488397a84c04f2894b
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

#server:
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/kanvas.p12
#    key-store-password: kanvas
#    key-alias: kanvas
