# Docker Compose containing whole system (infrastructure with spring boot microservices)
services:
  user-service-db:
    container_name: user-service-db
    image: postgres
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - user-service-postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  board-service-db:
    container_name: board-service-db
    image: postgres
    environment:
      POSTGRES_DB: board_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - board-service-postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  task-service-db:
    container_name: task-service-db
    image: postgres
    environment:
      POSTGRES_DB: task_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - task-service-postgres:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  notification-service-db:
    container_name: notification-service-db
    image: postgres
    environment:
      POSTGRES_DB: notification_service_db
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: gabriel
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - notification-service-postgres:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
      - kanvas-net
    restart: unless-stopped

  pgadmin:
    container_name: kanvas-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - kanvas-net
    restart: unless-stopped

  kafka:
    image: apache/kafka
    container_name: kanvas-kafka
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kanvas-net
#    ports:
#      - 9092:9092

  config-server:
    container_name: config-server
    image: kanvas/config-server
    networks:
      - kanvas-net

  discovery-server:
    container_name: discovery-server
    image: kanvas/discovery-server
    networks:
      - kanvas-net
    depends_on:
      - config-server
    ports:
      - 8761:8761

  user-service:
    container_name: user-service
    image: kanvas/user-service
    networks:
      - kanvas-net
    depends_on:
      - config-server
      - discovery-server
      - user-service-db
      - kafka

  board-service:
    container_name: board-service
    image: kanvas/board-service
    networks:
      - kanvas-net
    depends_on:
      - config-server
      - discovery-server
      - board-service-db
      - kafka

  task-service:
    container_name: task-service
    image: kanvas/task-service
    networks:
      - kanvas-net
    depends_on:
      - config-server
      - discovery-server
      - task-service-db
      - kafka

  notification-service:
    container_name: notification-service
    image: kanvas/notification-service
    networks:
      - kanvas-net
    depends_on:
      - config-server
      - discovery-server
      - notification-service-db
      - kafka

  websocket-service:
    container_name: websocket-service
    image: kanvas/websocket-service
    networks:
      - kanvas-net
    depends_on:
      - config-server
      - discovery-server
      - kafka

  gateway-service:
    container_name: gateway-service
    image: kanvas/gateway-service
    networks:
      - kanvas-net
    ports:
      - 8222:8222
    depends_on:
      - config-server
      - discovery-server
      - user-service
      - board-service
      - task-service
      - notification-service
      - websocket-service

networks:
  kanvas-net:
    driver: bridge

volumes:
  user-service-postgres:
  board-service-postgres:
  task-service-postgres:
  notification-service-postgres:
  pgadmin:
