spring:
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 10
        max-interval: 10000
        multiplier: 1.5
  application:
    name: task-service

application:
  ordering:
    step:
      column: 1000
      task: 1000